disabled = false
languageCode = "es"
languageName = "Spanish"
weight = 1
title = "Krpntrz"
[params]
  displayName = "ES"
  isoCode = "es"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Blog personal"
  copyright = "Ak4rp - 2025 CC by SA 4.0"

 [params.author]
   name = "Krpntrz"
   email = "krpntrz@disroot.org"
   image = "img/ICON.png"
   imageQuality = 96
   headline = "Bienvenid@ a mi blog personal."
#   bio = "Bienvenid@ a mi blog personal."
   links = [
#     { email = "mailto:krpntrz@protonmail.com" },
#     { link = "https://krpntrz.xyz/" },
      { mastodon = "https://mastodon.social/@ak4rp"}, 
#     { youtube = "https://youtube.com/username" },
   ]
